version: '3.9'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env.prod
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - foodgram-network

  backend:
    image: bignikkk/foodgram_backend
    env_file: .env.prod
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db
    networks:
      - foodgram-network
    platform: linux/amd64

  frontend:
    image: bignikkk/foodgram_frontend
    env_file: .env.prod
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    networks:
      - foodgram-network
    platform: linux/amd64

  gateway:
    image: bignikkk/foodgram_gateway
    env_file: .env.prod
    volumes:
      - static:/staticfiles/
      - media:/app/media
      - ./docs/:/usr/share/nginx/html/api/docs
    ports:
      - 8000:80
    networks:
      - foodgram-network
    depends_on:
      - backend
    platform: linux/amd64

networks:
  foodgram-network:
