version: '3.9'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - foodgram-network

  backend:
    image: bignikkk/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db
    networks:
      - foodgram-network

  frontend:
    image: bignikkk/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    networks:
      - foodgram-network

  gateway:
    image: bignikkk/foodgram_gateway
    volumes:
      - static:/staticfiles/
      - media:/app/media
    ports:
      - 8000:80
    networks:
      - foodgram-network

networks:
  foodgram-network:
