# Generated by Django 4.2.13 on 2024-05-26 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_favorite_favorite_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_list_items', to='recipes.recipe'),
        ),
    ]
