# Generated by Django 4.2.13 on 2024-05-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_favorite_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='shortlink',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
