# Generated by Django 4.2.13 on 2024-05-31 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_remove_recipe_shortlink_recipe_short_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='short_link',
        ),
    ]
