# Generated by Django 4.2.13 on 2024-05-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_remove_recipe_short_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_link',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
