# Generated by Django 4.2.13 on 2024-05-31 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_recipe_short_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShortRecipeLink',
        ),
    ]
