# Generated by Django 3.2 on 2024-05-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectuser',
            name='avatar',
            field=models.ImageField(default='default.png', null=True, upload_to='avatars/'),
        ),
    ]
