# Generated by Django 4.2.13 on 2024-05-27 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20240523_1009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ('-id',), 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterModelOptions(
            name='projectuser',
            options={'ordering': ('id',), 'verbose_name': 'Пользовaтель', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
